Repository HolyShaq/prismviz, pull requests merged in 2024-12, with the labels that each got.

#64 [feat] - frontend
  src/app/globals.css
  src/app/page.tsx
  src/components/CleanPage.tsx
  src/components/HeroPage.tsx
  src/components/UploadPage.tsx
  src/components/ai-panel/ai-panel.tsx
  src/components/ribbon/VisualizeRibbon.tsx
  src/lib/ChartContext.tsx
  src/lib/CsvContext.tsx
  tailwind.config.ts
Labels: bug, enhancement

#70 [feat] - help section
  public/PrismViz User Manual.pdf
  src/app/favicon.ico
  src/app/favicon1.ico
  src/app/page.tsx
Labels: bug, enhancement, help wanted

#79 [Feat] ai insights bar and column chart
  src/components/charts/Bar.tsx
  src/lib/ChartContext.tsx
Labels: enhancement
