Repository HolyShaq/prismviz, pull requests merged in 2024-11, with the labels that each got.

#24 Fix/users can now go back freely between step 1 and 2
  src/app/page.tsx
  src/components/Sidebar.tsx
Labels: help wanted

#26 Fix/step 3 bug jumping steps
  src/app/page.tsx
  src/components/CleanPage.tsx
  src/components/Sidebar.tsx
  src/components/UploadPage.tsx
  src/components/VisualizePage.tsx
Labels: enhancement

#28 Fix/step 2 being disabled when going back to step 1
  src/components/Sidebar.tsx
Labels: help wanted

#31 Add Ribbon Component
  src/app/page.tsx
  src/components/Ribbon.tsx
Labels: enhancement

#34 [feat] Set Up Project Branding Assets #21
  public/prismicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: enhancement, help wanted

#49 [fixed] - tooltip, icons, etc
  src/app/page.tsx
  src/components/Sidebar.tsx
  src/components/ribbon/CleanRibbon.tsx
  src/components/ribbon/Ribbon.tsx
  src/components/ribbon/RibbonButton.tsx
  src/components/ribbon/UploadRibbon.tsx
  src/components/ribbon/VisualizeRibbon.tsx
Labels: enhancement, fixed
